### ISSUE TITLE
Feature Request: World Restrictions

### ISSUE THREAD

**Issue by RillSoji** [qixils/minecraft-crowdcontrol#194]
Add a config to restrict the crowd control plugin on a per world basis. Ideally this would include permission nodes for LuckPerms to allow/disallow usage in certain worlds and these permissions could override the config settings. 

Usage scenario:
We currently run a server setup with Multiverse Core/Portals/NetherPortals where streamers each get their overworld/end/nether. Additionally we have a community hub world with quests and quest-worlds. We'd like to be able to disallow CrowdControl while in the hub world or other important public spaces. We'd also like to be able to allow Streamer A to visit Streamer B without fear of Streamer A's chat blowing up Streamer B's world. We'd be able to set the config to deny crowd control in streamer worlds but then setup luckperms to allow only Streamer B's crowd control to function for Streamer B in Streamer B's worlds. If they request for Streamer A to be allowed to use crowd control in their worlds then it's simple to just add the permission node to Streamer A too. 

Thanks for your consideration and hard work!

**Comment by qixils** [comment]
Would a WorldGuard flag be ok? Can be set globally, per world, or per region

**Comment by RillSoji** [comment]
That'd be a good fix! Though long term having a config and/or permission nodes would be fantastic because world guard is a bit of a resource hog.

**Comment by qixils** [comment]
Ah I see, hmm interesting I'll have to think how best to tackle this.

**Comment by qixils** [comment]
`crowdcontrol.use` permission node will be available in v3.3.7, releasing shortly after Minecraft 1.20.5
